### PR TITLE
Added FDACS dataset via upload

### PR DESCRIPTION
**Pull request by AjitWX**

### CODE REVIEW

**Comment by AjitWX** [comment]
Fdacs dataset added to TREC master

**Comment by AjitWX** [comment]
@Tamara729 Hey, Tamara. When you get a chance, can you please merge the FDACS dataset into the hemp-nutrition master.

**Review by Tamara729 — APPROVED** [review]
FDACS dataset merged into hemp-nutrition master.

**Review by Tamara729 — APPROVED** [review]
Merged FDACS dataset to hemp nutrition master

**Pull request merged**
